export const SET_TYPE = 'SET_TYPE'
export const REGISTER = 'REGISTER'
export const LOADING = 'LOADING'
export const SIGN_OUT = 'SIGN_OUT'
export const ERROR = 'ERROR'
export const SET_NAME = 'SET_NAME'

export const GET_TODOS = 'GET_TODOS'
export const CREATE_TODO = 'CREATE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
