version: "3.4"

services:
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    environment:
      API_ADDRESS: localhost:3001
      NODE_ENV: development
      PORT: 3000
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGO_DB_URI: mongodb://shuli:shulishuli@mongo:27017/usersDB
      SECRET: thisisawrongsecret
  mongo:
    image: mongo:4.4.6
    expose:
      - "27017"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: usersDB
      MONGO_INITDB_ROOT_USERNAME: shuli
      MONGO_INITDB_ROOT_PASSWORD: shulishuli