version: "3.4"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Web
    image: dev_next_redux_frontend
    restart: always
    volumes:
      - ./frontend:/app/frontend
    ports:
      - '3000:8080'
    environment:
      API_ADDRESS: localhost:3001
      NODE_ENV: development
      PORT: 3000
  backend:
    build: ./backend
    image: dev_next_redux_backend
    restart: always
    command: sh /usr/src/app/backend/start.sh && sh -c "--watch /usr/src/app/backend"
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - '3001:3000'
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGO_DB_URI: mongodb://localhost:27017/usersDB
      SECRET: thisisawrongsecret