import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next-Redux App</title>
        <meta name="description" content="Generated by create next app with Redux" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js-Redux!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
          Demo next-redux app
      </footer>
    </div>
  )
}
